name: Deploy the Blog stie to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies and building the code
      - uses: actions/checkout@v5
        run: npm install && npm run build

      - name: Deploy site to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
